### ISSUE TITLE
Keycloak cannot be disabled right now

### ISSUE THREAD

**Issue by cwiertniamichal** [onedata/charts#1]
https://github.com/onedata/charts/blob/cdd50ee1e5ae6f469f0b49580cbcd2e9169d5a57/stable/onezone/templates/deployment.yaml#L61

Error: YAML parse error on cross-support-job-3p/charts/onedata-3p/charts/onezone/templates/deployment.yaml: error converting YAML to JSON: yaml: line 29: did not find expected key
Traceback (most recent call last):
  File "/home/michal/onedataThings/tmp/mergeCharts/one-env/scripts/onenv_up.py", line 131, in <module>
    scenario_runner.run_scenario(env_config_output_dir)
  File "/home/michal/onedataThings/tmp/mergeCharts/one-env/scripts/scenario_runner.py", line 93, in run_scenario
    subprocess.check_call(helm_install_cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'install', '--namespace', 'default', '/home/michal/.one-env/deployments/2018.06.21-14.35.07/scenarios/scenario-1oz-1op', '-f', '/home/michal/.one-env/deployments/2018.06.21-14.35.07/scenarios/scenario-1oz-1op/MyValues.yaml', '--name', 'dev', '-f', '/home/michal/.one-env/deployments/2018.06.21-14.35.07/scenarios/scenario-1oz-1op/CustomConfig.yaml', '-f', '/home/michal/.one-env/deployments/2018.06.21-14.35.07/scenarios/scenario-1oz-1op/SourcesVal.yaml']' returned non-zero exit status 1

**Comment by groundnuty** [comment]
fixed in rewritten commit:
https://github.com/onedata/charts/commit/81fadf369f8b13f62d6e164613cb5b7409489250#diff-3b82da4ebbd7352804f677faf0a2bc52L61

please test it.
